sso:
  url: http://localhost:9191
email:
  name: admin@sipajak.com
server:
  port: 8081
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,image/x-icon,image/jpeg,image/png
    min-response-size: 1024
  http2:
    enabled: true
#  error:
#    whitelabel:
#      enabled: false
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/oauthdb?currentSchema=public
#    url: jdbc:postgresql://host.docker.internal:5432/oauthdb?currentSchema=public
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    tomcat:
      test-on-borrow: true
      test-while-idle: true
      time-between-eviction-runs-millis: 3600000
      validation-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  resources:
    cache:
      cachecontrol:
        max-age: 120
        cache-private: true
        cache-public: true
  thymeleaf:
    cache: false
  mail:
    host: smtp.gmail.com
    username: xxxxxxxx@gmail.com
    password: xxxxxx
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
path:
  directory: /opt/static
  assets: /opt/static