FROM openjdk:8-alpine

RUN apk update \
 && apk add fontconfig \
 && apk add ttf-dejavu
RUN ln -s /usr/lib/libfontconfig.so.1 /usr/lib/libfontconfig.so && \
    ln -s /lib/libuuid.so.1 /usr/lib/libuuid.so.1 && \
    ln -s /lib/libc.musl-x86_64.so.1 /usr/lib/libc.musl-x86_64.so.1
ENV LD_LIBRARY_PATH /usr/lib

COPY Admin-Sipajak.jar /app/running/Admin-Sipajak.jar
EXPOSE 8081
ENTRYPOINT ["java","-jar","/app/running/Admin-Sipajak.jar"]