api-server: http://103.121.251.2:8083/consume-api/cekNpwpAsp/
sso:
  url: http://localhost:9191
  auth: http://localhost:9191
app:
  url: http://localhost:${server.port}

redirect-uri: http://localhost:8080/auth/cek
security:
  oauth2:
    client:
      client-id: portalDev
      client-secret: portalDev
      user-authorization-uri: ${sso.url}/oauth/authorize
      access-token-uri: ${sso.auth}/oauth/token
      pre-established-redirect-uri: ${redirect-uri}
      registered-redirect-uri: ${redirect-uri}
      use-current-uri: false
      resource-ids: sipajak
    #      use-current-uri: false
    resource:
      token-info-uri: ${sso.auth}/oauth/check_token
      prefer-token-info: false
server:
  servlet:
    session:
      cookie:
        name: PPSESSION
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,image/x-icon,image/jpeg,image/png
    min-response-size: 1KB
    http2:
      enabled: true
  use-forward-headers: false
#  error:
#  whitelabel:
#    enabled: false
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    # url: jdbc:postgresql://host.docker.internal:5432/oauthdb?currentSchema=public
    url: jdbc:postgresql://localhost:5432/oauthdb?currentSchema=public
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    tomcat:
      test-on-borrow: true
      test-while-idle: true
      time-between-eviction-runs-millis: 3600000
      validation-query: SELECT 1
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  resources:
    cache:
      cachecontrol:
        max-age: 120
        cache-private: true
        cache-public: true
  thymeleaf:
    cache: false
path:
  directory: /opt/static

